version: "3.9"

services:
  api:
    build: ./routing-backend/
    container_name: routing-api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    environment:
      OSRM_URL: "http://osrm:5000"
      VROOM_URL: "http://vroom:3000"
    depends_on:
      - osrm
      - vroom

  vroom:
    image: ghcr.io/vroom-project/vroom-docker:v1.14.0
    container_name: vroom
    restart: always
    ports:
      - "3000:3000"
    environment:
      VROOM_ROUTER: "osrm"
      OSRM_URL: "http://osrm:5000"

  osrm:
    image: osrm/osrm-backend
    platform: linux/amd64
    container_name: osrm
    restart: always
    ports:
      - "5001:5000"
    volumes:
      - ./osrm-data:/data
    command: >
      osrm-routed --algorithm mld /data/slovenia-latest.osrm

